
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module mcu(

	//////////// CLOCK //////////
	input CLK,

	//////////// 7-segment decoder //////////
	output [6:0] HEX0,
	output [6:0] HEX1 ,
	output [6:0] HEX2 ,
	output [6:0] HEX3 ,
	
	//////////// LED /////////////
	output [9:0] LED,
	
	//////////// SWITCH //////////
	input [9:0] SW,
	
	//////////// BUTTON //////////
	input [2:0] BTN
	
);
//*******************************//
	wire [3:0] o_S;
	wire o_C;
	wire o_V;
// add module here
bits_adder_sub ads
	(
		.A(SW[7:4]),
		.B(SW[3:0]),
		.m(SW[8]),
		.S(o_S),
		.C(LED[8]),
		.V(LED[9])
	);
Binary_To_7Segment seg0(
    .i_Binary_Num(o_S),

    .o_Segment_A(HEX0[6]),
    .o_Segment_B(HEX0[5]),
    .o_Segment_C(HEX0[4]),
    .o_Segment_D(HEX0[3]),
    .o_Segment_E(HEX0[2]),
    .o_Segment_F(HEX0[1]),
    .o_Segment_G(HEX0[0])
);
Binary_To_7Segment seg2(
    .i_Binary_Num(SW[3:0]),

    .o_Segment_A(HEX2[6]),
    .o_Segment_B(HEX2[5]),
    .o_Segment_C(HEX2[4]),
    .o_Segment_D(HEX2[3]),
    .o_Segment_E(HEX2[2]),
    .o_Segment_F(HEX2[1]),
    .o_Segment_G(HEX2[0])
);
Binary_To_7Segment seg3(
    .i_Binary_Num(SW[7:4]),

    .o_Segment_A(HEX3[6]),
    .o_Segment_B(HEX3[5]),
    .o_Segment_C(HEX3[4]),
    .o_Segment_D(HEX3[3]),
    .o_Segment_E(HEX3[2]),
    .o_Segment_F(HEX3[1]),
    .o_Segment_G(HEX3[0])
);
assign HEX1 = 7'h7F;
assign LED[7:0] = SW[7:0];

//*******************************//

endmodule

module bits_adder_sub
	(
		input [3:0] A,
		input [3:0] B,
		input m,//1 sub,0 add
		
		output [3:0] S,
		output C,
		output V
	
	);
		wire [3:0] Bxor;
		wire [4:0] temp;
		wire [4:0] ct;
		assign Bxor = B ^ {4{m}};
		
		assign temp = A + Bxor + m ;
		assign ct[0]=m;
		assign ct[1]= (A[0]&&Bxor[0]||(ct[0]&&(A[0] ^ Bxor[0])));
		assign ct[2]= (A[1]&&Bxor[1]||(ct[1]&&(A[1] ^ Bxor[1])));
		assign ct[3]= (A[2]&&Bxor[2]||(ct[2]&&(A[2] ^ Bxor[2])));
		assign S = temp[3:0];
		assign C = temp[4];
		assign V = temp[4] ^ ct[3];

endmodule
module Binary_To_7Segment 
  (
   input [3:0] i_Binary_Num,
   output      o_Segment_A,
   output      o_Segment_B,
   output      o_Segment_C,
   output      o_Segment_D,
   output      o_Segment_E,
   output      o_Segment_F,
   output      o_Segment_G
   );
 
  reg [6:0]    r_Hex_Encoding = 7'h00;
  wire [3:0] i_Binary= (i_Binary_Num[3]) ? (~i_Binary_Num+1):i_Binary_Num;		//有signed bit
  
  // Purpose: Creates a case statement for all possible input binary numbers.
  // Drives r_Hex_Encoding appropriately for each input combination.
  always @(i_Binary_Num) 
  
    begin
      case (i_Binary) //有signed bit
        4'b0000 : r_Hex_Encoding <= 7'h7E;
        4'b0001 : r_Hex_Encoding <= 7'h30;
        4'b0010 : r_Hex_Encoding <= 7'h6D;
        4'b0011 : r_Hex_Encoding <= 7'h79;
        4'b0100 : r_Hex_Encoding <= 7'h33;          
        4'b0101 : r_Hex_Encoding <= 7'h5B;
        4'b0110 : r_Hex_Encoding <= 7'h5F;
        4'b0111 : r_Hex_Encoding <= 7'h70;//7
        4'b1000 : r_Hex_Encoding <= 7'h7F;
        4'b1001 : r_Hex_Encoding <= 7'h7B;
        4'b1010 : r_Hex_Encoding <= 7'h77;
        4'b1011 : r_Hex_Encoding <= 7'h1F;
        4'b1100 : r_Hex_Encoding <= 7'h4E;
        4'b1101 : r_Hex_Encoding <= 7'h3D;
        4'b1110 : r_Hex_Encoding <= 7'h4F;
        4'b1111 : r_Hex_Encoding <= 7'h47;
      endcase
    end // always @ (posedge i_Clk)
 
  // r_Hex_Encoding[7] is unused
  assign o_Segment_A = ~r_Hex_Encoding[0];
  assign o_Segment_B = ~r_Hex_Encoding[1];
  assign o_Segment_C = ~r_Hex_Encoding[2];
  assign o_Segment_D = ~r_Hex_Encoding[3];
  assign o_Segment_E = ~r_Hex_Encoding[4];
  assign o_Segment_F = ~r_Hex_Encoding[5];
  assign o_Segment_G = ~r_Hex_Encoding[6];
 
endmodule // Binary_To_7Segment

